[build]
  publish = "build/"
  command = "./scripts/netlify.sh"

[context.production.environment]
  APP_ENV = "production"

[context.stage.environment]
  APP_ENV = "staging"

[context.deploy-preview.environment]
  APP_ENV = "development"

[context.dev.environment]
  APP_ENV = "development"
