name: Dev action

on:
  push:
    branches:
      - dev

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: secrethub/actions/env-export@v0.1.0
        env:
          SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
          FIRST: secrethub://demo--strv/start/development/FIRST
          SECOND: secrethub://demo--strv/start/development/SECOND
          THIRD: secrethub://demo--strv/start/development/THIRD

      - name: Checkout
        uses: actions/checkout@master

      - name: Debug
        uses: hmarr/debug-action@master
