name: Dev action

on:
  push:
    branches:
      - dev

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        uses: allenevans/set-env@v1.0.0
        with:
          FIRST: ${{ secrets.DEV_FIRST }}
          SECOND: ${{ secrets.DEV_SECOND }}
          THIRD: ${{ secrets.DEV_THIRD }}

      - name: Checkout
        uses: actions/checkout@master

      - name: Debug
        uses: hmarr/debug-action@master
